# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Amy Unger
email: amy@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Mistakes as a Service Provider |
  coming soon GitHub ğŸ™ |
  ex-Heroku ğŸ’œ |
  ex-Getty Images ğŸ“¸ | she & her
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

footer_links:
  - title: Twitter
    url: https://twitter.com/cdwort
    icon: fab fa-twitter-square
  - title: GitHub
    url: https://github.com/cdwort
    icon: fab fa-github-square
  - title: LinkedIn
    utl: https://linkedin.com/in/cdwort
    icon: fab fa-linkedin

# Build settings
markdown: kramdown
remote_theme: "mmistakes/so-simple-theme@3.2.0"
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
